#ifndef FN
#define FN(name)
#endif

FN(AllocateMemory)
FN(CreateComputePipelines)
FN(CreateDescriptorPool)
FN(CreateDescriptorSetLayout)
FN(CreateDevice)
FN(CreatePipelineLayout)
FN(CreateShaderModule)
FN(DestroyDescriptorPool)
FN(DestroyDescriptorSetLayout)
FN(DestroyDevice)
FN(DestroyInstance)
FN(DestroyPipeline)
FN(DestroyPipelineLayout)
FN(DestroyShaderModule)
FN(EnumeratePhysicalDevices)
FN(FreeMemory)
FN(GetDeviceQueue)
FN(GetPhysicalDeviceFeatures2)
FN(GetPhysicalDeviceMemoryProperties)
FN(GetPhysicalDeviceProperties2)
FN(GetPhysicalDeviceQueueFamilyProperties)
FN(MapMemory)
FN(UnmapMemory)

#undef FN
